In [8]:
%pylab inline

import imageio
import matplotlib.pyplot as plt
from numpy import linalg

def homography_from_points(source_pts, target_pts):
    correspondences_count = len(source_pts)
    
    # we have two equations for each point correspondance
    A = zeros((2*correspondences_count, 9))
    for i in range(correspondences_count):
        A[i*2] = [
            -source_pts[i][0], -source_pts[i][1], -1, 
            0, 0, 0, 
            target_pts[i][0]*source_pts[i][0], target_pts[i][0]*source_pts[i][1], target_pts[i][0]
        ]
        A[i*2+1] = [
            0, 0, 0,
            -source_pts[i][0], -source_pts[i][1], -1, 
            target_pts[i][1]*source_pts[i][0], target_pts[i][1]*source_pts[i][1], target_pts[i][1]            
        ]
    
    U,S,V = linalg.svd(A)
    H = V[8].reshape((3,3)) 
        
    return H / H[2,2]

Populating the interactive namespace from numpy and matplotlib


In [9]:
w = 168
h = 66

pointListPoster=[array([0, 0, 1]), array([w, 0, 1]), array([w, h, 1]), array([0, h, 1])]
pointListTrain=[array([95, 170, 1]), array([238,171, 1]), array([235, 233, 1]), array([94, 239,
1])]

print homography_from_points(pointListPoster, pointListTrain)

[[  1.01341537e+00   8.52055632e-03   9.50000000e+01]
 [  1.22508924e-01   1.10564205e+00   1.70000000e+02]
 [  6.81617214e-04   2.51830548e-04   1.00000000e+00]]
